project:
  type: website

website:
  title: "Real Good Docs"
  page-navigation: true
  search: true

  navbar:
    background: black
    type: dark 
    border: true
    right:
      - href: https://github.com/realgoodresearch
        target: _blank
        text: GitHub
      - href: https://realgoodresearch.com
        target: _blank
        text: Real Good Research
    left:
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Research"
        href: research/index.qmd
  
  sidebar: 
    - id: bayesian-intro-sidebar
      title: "Bayesian Intro"
      path: teaching/bayesian_intro/
      contents: 
        - text: "Welcome"
          href: teaching/bayesian_intro/overview.qmd
        - text: "Table of Contents"
          href: teaching/bayesian_intro/toc.qmd
        - text: "Getting Started" 
          href: teaching/bayesian_intro/getting_started.qmd
        - section: "The Basics"
          contents: []
        - section: "Going Further"
          contents:
          - text: "Synthetic Controls"
            href: teaching/bayesian_intro/synthetic_controls.qmd

format:
  html:
    theme: 
      - cosmo
      - custom-theme.scss
    include-after-body: _footer.html
    toc: true
    number-sections: false
    bibliography: references.bib

execute:
  freeze: true

