project:
  type: website

website:
  title: "Real Good Docs"
  page-navigation: true
  search: true

  navbar:
    background: black
    type: dark 
    border: true
    right:
      - href: https://github.com/realgoodresearch
        target: _blank
        text: GitHub
      - href: https://realgoodresearch.com
        target: _blank
        text: Real Good Research

  sidebar:
    style: docked
    search: true
    collapse-level: 2
    contents:

      - section: "Teaching"
        href: teaching/index.qmd
        contents: 

          - section: "Bayesian Intro"
            href: teaching/bayesian_intro/index.qmd
            contents:
              - teaching/bayesian_intro/getting_started.qmd
              # - teaching/bayesian_intro/model_of_the_mean.qmd
              # - teaching/bayesian_intro/likelihood_prior_posterior.qmd
              # - teaching/bayesian_intro/linear_regression.qmd
              # - teaching/bayesian_intro/cross_validation.qmd
              # - teaching/bayesian_intro/synthetic_controls.qmd

      # - section: "Research"
      #   href: research/index.qmd
        
      #   contents:
      #     - section: "Gaza NowPop"
      #       href: research/gaza_nowpop/index.qmd
      #       contents:
      #         - research/gaza_nowpop/social_media.qmd
      #         - research/gaza_nowpop/polio_vaccination.qmd
      #         - research/gaza_nowpop/telecommunications.qmd

format:
  html:
    theme: 
      - cosmo
      - custom-theme.scss
    include-after-body: _footer.html
    toc: true
    number-sections: false
    bibliography: references.bib

execute:
  freeze: true

