---
title: "Getting Started"
subtitle: "An introduction to Bayesian statistics for applied research."
author: "Doug Leasure"
---

# Introduction

Welcome to the world of Bayesian statistics! 

The tutorials included in this Bayesian Intro will provide hands-on experience with Bayesian modelling using free and open source software--Stan and R. We use Stan because it is fast, flexible, very well documented, and supported by an active community of developers and users (see [Reading](#sec-reading) section). 


# Software

Before we get started, let's make sure that you have the right software installed on your computer. If you want to skip the installation and simply read along with the exercises, you can go ahead to the next section(s) now. When you're ready to run code on your own computer, just come back to this page to find links to the required software. 

You will need the following software to be able to run the example code on your own computer:  

1. R and <a href="https://posit.co/download/rstudio-desktop/" target="_blank">RStudio</a> or <a href="https://positron.posit.co/" target="_blank">Positron</a> (or your favourite R IDE)   
2. <a href="https://mc-stan.org/cmdstanr/articles/cmdstanr.html" target="_blank">CmdStanR and its dependencies</a>


# Reading {#sec-reading}

### Bayesian Statistics  

- <a href="https://github.com/rmcelreath/stat_rethinking_2024" target="_blank">Statistical Rethinking Lectures</a> (and book) by Richard McElreath  
- <a href="https://www.bayesrulesbook.com/" target="_blank">Bayes Rules!</a> by Johnson, Ott, and Dogucu.  


### Stan Software  

- <a href="https://mc-stan.org/learn-stan/tutorials.html" target="_blank">Introductory Stan tutorials, videos, and podcasts</a>  
- <a href="https://mc-stan.org/docs/" target="_blank">Stan Documentation</a>  
- <a href="https://discourse.mc-stan.org/" target="_blank">Stan User Forums</a>  
- <a href="https://mc-stan.org/learn-stan/case-studies.html#volume-5-2018" target="_blank">Stan Case Studies</a>  
- <a href="https://mc-stan.org/" target="_blank">Stan website</a> (collects all of the above together, with some deeper-dive materials as well)  


### Books  

- Gelman A, Carlin JB, Stern HS, Dunson DB, Vehtari A, Rubin D. 2013. Bayesian Data Analysis. Chapman & Hall/CRC Texts in Statistical Science. <a href="https://sites.stat.columbia.edu/gelman/book/BDA3.pdf" target="_blank">https://sites.stat.columbia.edu/gelman/book/BDA3.pdf</a>  
- McElreath R. 2015. Statistical Rethinking: A Bayesian course with examples in R and Stan. Chapman & Hall/CRC Texts in Statistical Science. <a href="https://civil.colorado.edu/~balajir/CVEN6833/bayes-resources/RM-StatRethink-Bayes.pdf" target="_blank">https://civil.colorado.edu/~balajir/CVEN6833/bayes-resources/RM-StatRethink-Bayes.pdf</a>  
- Lambert B. A student's guide to Bayesian statistics. Sage. <a href="https://study.sagepub.com/lambert" target="_blank">https://study.sagepub.com/lambert</a>.  
- Hobbs NT, Hooten MB. 2015. Bayesian Models: A statistical primer for ecologists. Princeton University Press. Request full text pdf from authors via ResearchGate: <a href="https://www.researchgate.net/publication/283813602_Bayesian_Models_A_Statistical_Primer_for_Ecologists" target="_blank">https://www.researchgate.net/publication/283813602_Bayesian_Models_A_Statistical_Primer_for_Ecologists</a>.  


