server {
  listen 80;
  server_name realgoodresearch.com www.realgoodresearch.com;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl http2;
  server_name realgoodresearch.com www.realgoodresearch.com;

  ssl_certificate /etc/letsencrypt/live/realgoodresearch.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/realgoodresearch.com/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:10m;
  ssl_protocols TLSv1.2 TLSv1.3;

  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  add_header Content-Security-Policy "upgrade-insecure-requests; block-all-mixed-content" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header Referrer-Policy "strict-origin-when-cross-origin" always;

  root /usr/share/nginx/html;
  index index.html;

  location = /favicon.ico {
    try_files /favicon.ico /assets/images/logo/favicon.ico =404;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
